/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "./rpcvec.h"

bool_t
xdr_vec (XDR *xdrs, vec *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vec_val, (u_int *) &objp->vec_len, 255,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_min_and_max (XDR *xdrs, min_and_max *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vec_and_num (XDR *xdrs, vec_and_num *objp)
{
	register int32_t *buf;

	 if (!xdr_vec (xdrs, &objp->vector))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->number))
		 return FALSE;
	return TRUE;
}
