/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "./rpcvec.h"

bool_t
xdr_vec (XDR *xdrs, vec *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->vector_array, sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->vector_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vec_and_num (XDR *xdrs, vec_and_num *objp)
{
	register int32_t *buf;

	 if (!xdr_vec (xdrs, &objp->vector))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->number))
		 return FALSE;
	return TRUE;
}
