human_files:
	cc ./rpcvec_client.c ../rpc/rpcvec_clnt.c -lnsl -o rpcvec_client
	cc ./rpcvec_server.c ../rpc/rpcvec_svr.c -lnsl -o rpcvec_server
#Binary files are moved to the bin directory
	mv rpcvec_client rpcvec_server ../../bin
